import sailly from "../assets/gallery/sailly_blank.png"; 
import asador from "../assets/gallery/asador_blank.png"; 
import bobaLife from "../assets/gallery/bobaLife_blank.png"; 
import ioniq5 from "../assets/gallery/ioniq5_blank.png"; 

export const projects = [
    {
        id: 1, 
        img: sailly, 
        alt: "sail.ly snapshot",
        title: "sailly", 
        description: "Dream in open waters. SAIL.LY is a web app for beginner-to-experienced sailors that want to enjoy a day out on the water. App allows users to check on their favorite sailing clubs for sailing conditions based on real-time weather data, integrated with Weather API.",
        btnTitle: "let's go for a sail",
        btnUrl: "sailly",
        liveUrlTitle: "Live", 
        liveUrl: "https://sail-ly.netlify.app", 
        gitHubTitle: "Repo",
        gitHubUrl: "https://github.com/danveb/sail.ly", 
    },
    {
        id: 2, 
        img: asador, 
        alt: "asador.ly snapshot", 
        title: "asador", 
        description: "Ever wondered what asado means in Buenos Aires? Asador is all about sharing the joy of the best parrillas (steakhouses). Users are greeted with a live, open-source map with custom pins. Signing up for an account allows users to pin their favorite parrillas.",
        btnTitle: "hello asador",
        btnUrl: "asador",
        liveUrlTitle: "Live", 
        liveUrl: "https://asador.netlify.app", 
        gitHubTitle: "Repo",
        gitHubUrl: "https://github.com/danveb/asador.ly", 
    },
    {
        id: 3, 
        img: bobaLife, 
        alt: "bobaLife snapshot", 
        title: "bobalife", 
        description: "Who enjoys sipping an ice-cold boba milk tea at any time of the day? bobaLife is an e-commerce web app designed for a fictitous boba shop. This app incorporates working cart/checkout process and integration of Stripe mobile payments.",
        btnTitle: "wanna boba?",
        btnUrl: "bobalife",
        liveUrlTitle: "Live", 
        liveUrl: "https://bobalife.netlify.app", 
        gitHubTitle: "Repo",
        gitHubUrl: "https://github.com/danveb/bobaLife", 
    },
    {
        id: 4, 
        img: ioniq5, 
        alt: "ioniq5 snapshot", 
        title: "ioniq5", 
        description: "App designed for users who want to search deliveries of 2022 Hyundai IONIQ 5 to local dealerships. User can fill in the zipcode and radius for searching. Data is fetched from Hyundai USA's API and key details are displayed on a table.",
        btnTitle: "ioniq ftw",
        btnUrl: "ioniq5",
        liveUrlTitle: "Live", 
        liveUrl: "https://ioniq5-lookup.netlify.app/", 
        gitHubTitle: "Repo",
        gitHubUrl: "https://github.com/danveb/ioniq5", 
    },
]

// export const projects = [
//     {
//         id: 1, 
//         img: sailly, 
//         title: "sail.ly", 
//         description: "Dream in open waters. SAIL.LY is a web app for beginner-to-experienced sailors that want to enjoy a day out on the water. App allows users to check on their favorite sailing clubs for sailing conditions based on real-time weather data, integrated with Weather API.",
//         buttons: ["React", "CSS", "Node", "Express", "PostgreSQL", "Weather API", "MapboxGL API", "Netlify"], 
//         backgroundColor: "var(--maximum-yellow-red)", 
//         liveSite: "https://sail-ly.netlify.app", 
//         githubRepo: "https://github.com/danveb/sail.ly", 
//         target: "_blank", 
//         rel: "noreferrer noopener", 
//     }, 
//     {
//         id: 2, 
//         img: bobaLife, 
//         title: "bobaLife", 
//         description: "Who enjoys sipping an ice-cold boba milk tea at any time of the day? bobaLife is an e-commerce web app designed for a fictitous boba shop. This app incorporates working cart/checkout process and integration of Stripe mobile payments.",
//         buttons: ["React", "Redux", "Styled Components", "Express", "JWT", "Stripe-js", "MongoDB", "Netlify"], 
//         backgroundColor: "var(--fuzzy-wuzzy)", 
//         liveSite: "https://bobalife.netlify.app", 
//         githubRepo: "https://github.com/danveb/bobalife", 
//         target: "_blank", 
//         rel: "noreferrer noopener", 
//     }, 
//     {
//         id: 3, 
//         img: asador, 
//         title: "asador", 
//         description: "Ever wondered about asado (barbeque) in Buenos Aires? Asador is all about sharing the joy of the best parrillas (steakhouses). Users are greeted with a live map with pins. Signing up for an account allows users to pin their favorite parrillas.", 
//         buttons: ["React", "Redux", "Sass", "Express", "JWT", "MapboxGL API", "MongoDB", "Netlify"],
//         backgroundColor: "var(--raisin-black)", 
//         liveSite: "https://asador.netlify.app", 
//         githubRepo: "https://github.com/danveb/asador.ly", 
//         target: "_blank", 
//         rel: "noreferrer noopener", 
//     }, 
//     {
//         id: 4, 
//         img: ioniq5, 
//         title: "ioniq5 Lookup", 
//         description: "App designed for users who want to search deliveries of 2022 Hyundai IONIQ 5 to local dealerships. User can fill in the zipcode and radius for searching. Data is fetched from Hyundai USA's API and key details are displayed on a table.", 
//         buttons: ["React", "Sass", "MUI", "Express", "Hyundai USA API", "Netlify"], 
//         backgroundColor: "var(--ny-pink)", 
//         liveSite: "https://ioniq5-lookup.netlify.app/", 
//         githubRepo: "https://github.com/danveb/ioniq5", 
//         target: "_blank", 
//         rel: "noreferrer noopener", 
//     }, 
//     // {
//     //     id: 5, 
//     //     img: sailmasterII, 
//     //     title: "Sail Master II", 
//     //     description: "App built for sailors and water sports’ enthusiasts that have a common goal to share the joy in sailing. App informs sailing conditions based on current wind parameters; it makes it the perfect companion to enjoy the day on the water.", 
//     //     buttons: ["React", "Express", "JWT", "Weather API", "PostgreSQL", "Surge"], 
//     //     backgroundColor: "var(--cadet-blue-crayola)", 
//     //     liveSite: "https://lighthouse-sailor.surge.sh/", 
//     //     githubRepo: "https://github.com/danveb/sail-master-II", 
//     //     target: "_blank", 
//     //     rel: "noreferrer noopener", 
//     // }, 
//     {
//         id: 5, 
//         img: laptopMain, 
//         title: "Check my GitHub", 
//         description: "Check my GitHub link to view more projects where I continue to build user-focused apps. Follow the link below!", 
//         buttons: [], 
//         backgroundColor: "var(--maximum-blue)", 
//         liveSite: "", 
//         githubRepo: "https://github.com/danveb", 
//         target: "_blank", 
//         rel: "noreferrer noopener", 
//     }, 
// ]; 